server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      # Ruta para logistica
      - id: service-logistica
        uri: http://localhost:8085
        predicates:
        - Path=/api/v3/logistica/**
      # Ruta para reservas
      - id: service-reservas
        uri: http://localhost:8084
        predicates:
        - Path=/api/v2/reservas/**